spring:
  profiles:
    active: @profileActive@
  application:
    name: seata-at-account
mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/at-account/at-account.log
    max-size: 10MB