spring:
  profiles:
    active: @profileActive@
  application:
    name: seata-tcc-order
mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/tcc-order/tcc-order.log
    max-size: 10MB