spring:
  profiles:
    active: @profileActive@
  application:
    name: seata-at-business
mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/at-business/at-business.log
    max-size: 10MB