spring:
  profiles:
    active: @profileActive@
  application:
    name: seata-tcc-account
mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/tcc-account/tcc-account.log
    max-size: 10MB