spring:
  profiles:
    active: @profileActive@
  application:
    name: seata-at-order
mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/at-order/at-order.log
    max-size: 10MB